### ISSUE TITLE
[BUG] Noticeboard contracts don't respect "Allow city spawns" option.

### ISSUE THREAD

**Issue by Sneakpeakcss** [Aelto/W3_RandomEncounters_Tweaks#71]
**Describe the bug**
Getting a contract from a noticeboard in Novigrad starts it inside the town, often in unavailable spots. 

**To Reproduce**
1. Take a contract in Novigrad and wait for it to start.

**Expected behavior**
Quest should start after leaving Novigrad(?).

**Screenshots**
https://imgur.com/a/9lwNcMK

**Random Encounters version used:**
 RER V2.5 used.

**Mods you use:**
 - Random Encounters Reworked

**Additional context**
It happened with both Monster nest and Monster tracks type of quests. The second one triggered geralts animation inside of the 'Butcher's Yard theater' but the tracks didn't even appear. 

Also a question. Does "Keybind - Trigger an encounter" function properly in 2.5 release? Disable/Enable or Settings Reload works without a problem, but pressing "IK_0=(Action=RandomEncounter)" doesn't seem to trigger anything for me.

**Comment by Aelto** [comment]
@Sneakpeakcss i had the time to test the "Encounter trigger" keybind and it is working as intended. Pressing the key tells RER to put the delay to 5 seconds, which means a new encounter will start 5 seconds after you have pressed the key. And as i said sometimes the encounters are cancelled due to external factors:
> Then this encounter could spawn anywhere or even be cancelled due to region constraints, settlement constraints or bestiary constraints.
